config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  delete '/sessions', to: 'sessions#destroy'

  resources :gists

end

app/models/gist_form.rb
class GistForm
  attr_accessor :description, :file_name, :file_contents

  include ActiveModel::Model

  validates :description, :file_name, :file_contents, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def user_signed_in?
    session[:user_id].present?
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  helper_method :user_signed_in?
  helper_method :current_user

  def require_sign_in
    unless user_signed_in?
      flash[:info] = "You must sign in."
      redirect_to root_path
    end
  end

  def clear_gists_cache
    Rails.cache.delete_matched "^https://api.github.com/gists"
  end
end

app/controllers/gists_controller.rb
require_dependency "git_hub_api/client"

class GistsController < ApplicationController

  before_filter :require_sign_in

  def index
    @gists = github_api_client.gists(page: params[:page])
  end

  def new
    @gist_form = GistForm.new
  end

  def create
    @gist_form = GistForm.new(gist_form_params)
    if @gist_form.valid?
      gist_info = github_api_client.create_private_gist(@gist_form.description,
                                                        @gist_form.file_name,
                                                        @gist_form.file_contents)
      flash[:info] = "Your gist has been created and can be viewed at this" +
                     " url: #{gist_info.url}"

      clear_gists_cache

      redirect_to gist_path(gist_info.id)
    else
      render :new
    end
  rescue GitHubAPI::RequestFailure => e
    flash[:danger] = e.message
    render :new
  end

  def show
    client = GitHubAPI::Client.new(current_user.token)
    @gist = client.gist_info(params[:id])
  rescue GitHubAPI::NonexistentGist => e
    flash.now[:danger] = e.message
    render status: 404
  end

  def destroy
    github_api_client.delete_gist(params[:id])
    flash[:info] = 'The gist was deleted.'

    clear_gists_cache

    redirect_to gists_path
  rescue GitHubAPI::Error => e
    flash[:danger] = "The gist could not be deleted: #{e.message}"
    redirect_to gists_path
  end

  private

  def gist_form_params
    params.require(:gist_form).permit(:description, :file_name, :file_contents)
  end

  def github_api_client
    @github_api_client ||= GitHubAPI::Client.new(current_user.token)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    @user = User.find_or_create_by!(remote_id: auth.uid, provider: 'github') do |user|
      binding.pry
      user.name = auth.info.nickname
      user.token = auth.credentials.token
    end
    session[:user_id] = @user.id
    flash[:info] = 'You have signed in with GitHub.'
    redirect_to root_path
  end

  def failure
    flash[:danger] = 'Authorization Failed.'
    redirect_to root_path
  end

  def destroy
    reset_session
    flash[:info] = 'You have been signed out.'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gists/index.html.erb
<div class="row clearfix">
  <div class="col-lg-12">
    <h1>Gists</h1>
    <p class="pull-left">Showing page <%= @gists.page %> of <%= pluralize(@gists.total_pages, "page") %>.</p>
    <p class="pull-right">
      <%= link_to "Create a new Gist", new_gist_path, class: 'btn btn-primary' %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <table class="table">
      <thead>
        <tr>
          <th>Description</th>
          <th>Public?</th>
          <th>Created</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @gists.items.each do |gist| %>
          <tr>
            <td><%= link_to gist.description.present? ? gist.description : "untitled", gist_path(gist.id) %></td>
            <td><% if gist.public %><span class="glyphicon glyphicon-eye-open" /><% end %></td>
              <td><%= gist.created_at %></td>
              <td class="delete-button"><%= link_to 'Delete', gist_path(gist.id), method: :delete, class: 'btn btn-danger', data: { confirm: 'Delete this gist?'} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <nav>
      <ul class="pager">
        <% if @gists.page > 1 %>
          <li class="previous">
            <%= link_to(page: @gists.page - 1) do %>
              <span class="glyphicon glyphicon-arrow-left"></span> Previous Page
            <% end %>
          </li>
        <% end %>
        <% if @gists.page < @gists.total_pages %>
          <li class="next">
            <%= link_to(page: @gists.page + 1) do %>
              Next Page <span class="glyphicon glyphicon-arrow-right"></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/gists/new.html.erb
<h1>Create a new Gist</h1>

<%= form_for @gist_form, url: gists_path, class:"form" do |f| %>

  <% if @gist_form.errors.any? %>
    <ul>
      <% @gist_form.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :file_name %>
    <%= f.text_field :file_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :file_contents %>
    <%= f.text_area :file_contents, class: "form-control" %>
  </div>

  <%= button_tag "Create Gist", name: nil, class: "btn btn-primary" %>
<% end %>

app/views/gists/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <% if @gist %>
      <h1><%= @gist.description %></h1>
      <% @gist.files.each do |file| %>
        <h3><%= file.name %> (<%= file.language %>)</h3>
        <pre><code><%= file.content %></code></pre>
      <% end %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Web APIs</h1>

<% if user_signed_in? %>

  <h2>Welcome!</h2>

<% else %>

  <p>Sign in with GitHub!</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReportsWeb</title>
  <%= javascript_include_tag "//code.jquery.com/jquery-2.1.3.min.js" %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default navbar-static-top">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Web APIs</a>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Gists", gists_path %></li>
      </ul>
      <% if user_signed_in? %>
        <p class="navbar-text">Signed in as <%= current_user.name %>. <%= link_to "Sign out", sessions_path, method: :delete %></p>
      <% else %>
        <p class="navbar-text"><%= link_to "Sign in with GitHub", '/auth/github' %></p>
      <% end %>
    </nav>
    <div class="row">
      <div class="col-sm-12 pull-right">
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: "alert alert-#{name}" %>
        <% end -%>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>